name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Application
        run: npm start

      - name: Run Tests
        run: npm test

docker-build-and-push:
  needs: build
  runs-on: ubuntu-latest

  steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     - name: Docker Login
       run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
       run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/simple-ci:latest" .

     - name: Push Docker Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/simple-ci:latest"      